#' Adds Outliers to a Vector, Matrix or Data Frame
#'
#' @description Takes a vector, matrix or data frame and replaces some numeric values by outliers. 
#' 
#' @author Michael Mayer
#' 
#' @importFrom stats sd
#' @param x A vector, matrix or \code{data.frame}.
#' @param p Proportion of outliers to add to \code{x}. In case \code{x} is a \code{data.frame}, \code{p} can also be a vector of probabilities per column or a named vector (see examples).
#' @param sd_factor Each outlier is generated by shifting the original value by a normal random variable with \code{sd_factor} times the original sample standard deviation.
#' @param seed An integer seed.
#'
#' @return \code{x} with outliers.
#' 
#' @export
#'
#' @examples 
#' generateOutlier(1:10, seed = 3345)
#' generateOutlier(cbind(1:10, 10:1), p = 0.2)
#' head(generateOutlier(iris))
#' head(generateOutlier(iris, p = 0.2))
#' head(generateOutlier(iris, p = c(0, 1, 0.5, 0.5, 0.5)))
#' head(generateOutlier(iris, p = c(Sepal.Length = 1)))
generateOutlier <- function(x, p = 0.1, sd_factor = 5, seed = NULL) {
  stopifnot(p >= 0, p <= 1, is.atomic(x) || is.data.frame(x))
  
  if (!is.null(seed)) {
    set.seed(seed)  
  }
  
  generateOutlierVec <- function(z, p) {
    if (!is.numeric(z)) {
      return(z)
    }
    n <- length(z)
    m <- round(p * n)
    z[sample(n, m)] <- z[m] + rnorm(m, sd_factor * sd(z, na.rm = TRUE))
    z
  }
  
  # vector or matrix
  if (is.atomic(x)) {
    return(generateOutlierVec(x, p))
  } 
  
  # data frame
  v <- if (is.null(names(p))) names(x) else intersect(names(p), names(x))
  x[, v] <- Map(generateOutlierVec, x[, v, drop = FALSE], p)

  x
}
